//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKS.Library.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CoreResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CoreResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MKS.Library.Resources.CoreResources", typeof(CoreResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticatedUser.
        /// </summary>
        public static string AUTHENTICATE_USER {
            get {
                return ResourceManager.GetString("AUTHENTICATE_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationType.
        /// </summary>
        public static string AUTHENTIFICATION_TYPE {
            get {
                return ResourceManager.GetString("AUTHENTIFICATION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateByPassRouting.
        /// </summary>
        public static string BYPASS_ROUTING {
            get {
                return ResourceManager.GetString("BYPASS_ROUTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DefaultCacheDuration.
        /// </summary>
        public static string CACHE_DURATION {
            get {
                return ResourceManager.GetString("CACHE_DURATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateCaching.
        /// </summary>
        public static string CACHING {
            get {
                return ResourceManager.GetString("CACHING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DebugMode.
        /// </summary>
        public static string DEBUG_MODE {
            get {
                return ResourceManager.GetString("DEBUG_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez identifié un classe de configuration avec une connexion à null.
        /// </summary>
        public static string DESIGN_BD_CONNECTION {
            get {
                return ResourceManager.GetString("DESIGN_BD_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environnement.
        /// </summary>
        public static string ENVIRONNEMENT {
            get {
                return ResourceManager.GetString("ENVIRONNEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre devez overrider la méthode {0} dans votre classe de Mapping..
        /// </summary>
        public static string EX0001 {
            get {
                return ResourceManager.GetString("EX0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous utilisez une validation personalisée sans avoir défini la validation à effectuer.
        /// </summary>
        public static string EX0002 {
            get {
                return ResourceManager.GetString("EX0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun contrat n&apos;est défini pour ce connecteur..
        /// </summary>
        public static string EX0003 {
            get {
                return ResourceManager.GetString("EX0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il n&apos;y a aucun URL de défini ou d&apos;actif pour les contrats dans les configurations..
        /// </summary>
        public static string EX0004 {
            get {
                return ResourceManager.GetString("EX0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les Urls des contrats suivants sont manquants :.
        /// </summary>
        public static string EX0005 {
            get {
                return ResourceManager.GetString("EX0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez spécifier un IRoutingUsage dans votre connecteur. Utilisez la méthode SetRouting pour y parvenir..
        /// </summary>
        public static string EX0006 {
            get {
                return ResourceManager.GetString("EX0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de communiquer avec le service {0}..
        /// </summary>
        public static string EX0007 {
            get {
                return ResourceManager.GetString("EX0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Système client inconnu.
        /// </summary>
        public static string EX0008 {
            get {
                return ResourceManager.GetString("EX0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Utilisateur client inconnu.
        /// </summary>
        public static string EX0009 {
            get {
                return ResourceManager.GetString("EX0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Machine client inconnu.
        /// </summary>
        public static string EX0010 {
            get {
                return ResourceManager.GetString("EX0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Système client : .
        /// </summary>
        public static string EX0011 {
            get {
                return ResourceManager.GetString("EX0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Usager client : .
        /// </summary>
        public static string EX0012 {
            get {
                return ResourceManager.GetString("EX0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Machine client : .
        /// </summary>
        public static string EX0013 {
            get {
                return ResourceManager.GetString("EX0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de trouver l&apos;URI de l&apos;élément {0} dans la balise &quot;MKSServicesWCF&quot; du fichier de configuration de l&apos;application..
        /// </summary>
        public static string EX0014 {
            get {
                return ResourceManager.GetString("EX0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L&apos;URI de l&apos;élément {0} dans la balise &quot;MKSServicesWCF&quot; du fichier de configuration de l&apos;application est incorrect..
        /// </summary>
        public static string EX0015 {
            get {
                return ResourceManager.GetString("EX0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le paramètre d&apos;entrée du proxy a la valeur Null..
        /// </summary>
        public static string EX0016 {
            get {
                return ResourceManager.GetString("EX0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;héberger le service demandé à l&apos;adresse suivante : {0}.
        /// </summary>
        public static string EX0017 {
            get {
                return ResourceManager.GetString("EX0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;appeler le service à l&apos;adresse suivante {0}.
        /// </summary>
        public static string EX0018 {
            get {
                return ResourceManager.GetString("EX0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un appel a été fait au service à l&apos;adresse suivante : {0}.
        /// </summary>
        public static string EX0019 {
            get {
                return ResourceManager.GetString("EX0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez définir la clef &lt;add key=&quot;CodeSysteme&quot; value=&quot;Insérez Le code de système ici&quot;/&gt; dans la balise AppSettings de votre fichier de configuration.
        /// </summary>
        public static string EX0020 {
            get {
                return ResourceManager.GetString("EX0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la validation. Soit l&apos;objet à valider ne comporte pas la méthode ou la propriété testée, soit la valeur de la propriété est à Null..
        /// </summary>
        public static string EX0021 {
            get {
                return ResourceManager.GetString("EX0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible d&apos;obtenir l&apos;en-tête du message, vérifiez que votre service possède bien le Behavior de communication MKS..
        /// </summary>
        public static string EX0022 {
            get {
                return ResourceManager.GetString("EX0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la validation de type {0} sur la propriété {1} de l&apos;objet {2}..
        /// </summary>
        public static string EX0023 {
            get {
                return ResourceManager.GetString("EX0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez être dans un appel service pour avoir accès aux propriétés &quot;Client&quot;..
        /// </summary>
        public static string EX0024 {
            get {
                return ResourceManager.GetString("EX0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur lors de la validation: L&apos;objet à valider de type {0} est NULL..
        /// </summary>
        public static string EX0025 {
            get {
                return ResourceManager.GetString("EX0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez être dans un appel service pour utiliser cette méthode..
        /// </summary>
        public static string EX0026 {
            get {
                return ResourceManager.GetString("EX0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallByName() : Nom de méthode ou de propriété inexistant ou Null : {0}.
        /// </summary>
        public static string EX0027 {
            get {
                return ResourceManager.GetString("EX0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le délai de {0} secondes a expiré..
        /// </summary>
        public static string EX0028 {
            get {
                return ResourceManager.GetString("EX0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Type Does Not Have Property.
        /// </summary>
        public static string EX0029 {
            get {
                return ResourceManager.GetString("EX0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Property is Not String Type.
        /// </summary>
        public static string EX0030 {
            get {
                return ResourceManager.GetString("EX0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a member access.
        /// </summary>
        public static string EX0031 {
            get {
                return ResourceManager.GetString("EX0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a lambda expression.
        /// </summary>
        public static string EX0032 {
            get {
                return ResourceManager.GetString("EX0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a method call.
        /// </summary>
        public static string EX0033 {
            get {
                return ResourceManager.GetString("EX0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsAuthenticated.
        /// </summary>
        public static string IS_AUTHENTICATED {
            get {
                return ResourceManager.GetString("IS_AUTHENTICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MKSServicesWCF.
        /// </summary>
        public static string MKSServicesWCF {
            get {
                return ResourceManager.GetString("MKSServicesWCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationCode.
        /// </summary>
        public static string SYSTEM_CODE {
            get {
                return ResourceManager.GetString("SYSTEM_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationUser.
        /// </summary>
        public static string USER_CODE {
            get {
                return ResourceManager.GetString("USER_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionFrameWork.
        /// </summary>
        public static string VERSION_FRAMEWORK {
            get {
                return ResourceManager.GetString("VERSION_FRAMEWORK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VersionService.
        /// </summary>
        public static string VERSION_SERVICE {
            get {
                return ResourceManager.GetString("VERSION_SERVICE", resourceCulture);
            }
        }
    }
}
