//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MKS.Presenter.Model {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PresenterResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PresenterResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MKS.Presenter.Model.PresenterResources", typeof(PresenterResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le nom &apos;{0}&apos;  dans l&apos;attribut de l&apos;objet  ne correspond pas avec la propriété de l&apos;objet &apos;{1}&apos;. Vérifier votre attribut dans votre vue..
        /// </summary>
        public static string DESIGN_ERR_002 {
            get {
                return ResourceManager.GetString("DESIGN_ERR_002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune classe de processus n&apos;est assignée au présentateur..
        /// </summary>
        public static string DESIGN_ERR_004 {
            get {
                return ResourceManager.GetString("DESIGN_ERR_004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez oublié d&apos;ajouter la clé SecurityNoAccess dans le fichier de configuration au niveau du AppSettings. Cette clé permet d&apos;identifier le chemin où rediriger la page lorsque l&apos;usager n&apos;a aucun accès..
        /// </summary>
        public static string DESIGN_ERR_005 {
            get {
                return ResourceManager.GetString("DESIGN_ERR_005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucun objet n&apos;a été passé ou est à null pour l&apos;autovalidation. Veuillez passer un objet non null..
        /// </summary>
        public static string DESIGN_ERR_007 {
            get {
                return ResourceManager.GetString("DESIGN_ERR_007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La référence de la vue ne peut pas être null..
        /// </summary>
        public static string DESIGN_ERR_008 {
            get {
                return ResourceManager.GetString("DESIGN_ERR_008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de validation d&apos;affaire.
        /// </summary>
        public static string ERR_BUSINESSVALIDATION {
            get {
                return ResourceManager.GetString("ERR_BUSINESSVALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue, veuillez contacter le responsable du système..
        /// </summary>
        public static string ERR_EXCEPTION {
            get {
                return ResourceManager.GetString("ERR_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ressource que vous voulez accéder est réservé par un autre utilisateur.
        /// </summary>
        public static string ERR_RESERVATION {
            get {
                return ResourceManager.GetString("ERR_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur techique est survenue.
        /// </summary>
        public static string ERR_TECHNICAL {
            get {
                return ResourceManager.GetString("ERR_TECHNICAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erreur de validation.
        /// </summary>
        public static string ERR_VALIDATION {
            get {
                return ResourceManager.GetString("ERR_VALIDATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information du système.
        /// </summary>
        public static string SYSTEM_INFO {
            get {
                return ResourceManager.GetString("SYSTEM_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string VALIDATION_SUCCESS {
            get {
                return ResourceManager.GetString("VALIDATION_SUCCESS", resourceCulture);
            }
        }
    }
}
